### ISSUE TITLE
PHP 7 support?

### ISSUE THREAD

**Issue by jgraup** [ideasonpurpose/basic-wordpress-box#8]
Any chance you'll add support for [PHP 7](http://php.net/archive/2015.php#id2015-12-03-1)? Or would that require a ton more work than just adding `ppa:ondrej/php-7.0` to [php.yml](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php.yml)?

**Comment by joemaller** [comment]
I think it might be a little more complicated since all the [additional PHP packages](https://github.com/ideasonpurpose/basic-wordpress-box/blob/master/ansible/roles/php/tasks/php.yml#L14-L21) are prefixed with `php5`. It's on my list though. I'm curious to see how quickly this version will gain traction, PHP7 sounds like it brings a lot of major improvements.

**Comment by joemaller** [comment]
Not a lot to go by, but this looks like it's working. Needs more testing and I want to see how quickly the big managed hosts upgrade before deploying this. But if anyone wants to try it out, just clone the repo and run `./build.sh` and then reference `basic-wp` from a Vagrantfile.

**Comment by joemaller** [comment]
Done!
